cloudprovider: harvester
cloudCredentialSecretName: cattle-global-data:deathstar
cloudProviderConfigSecretName: secret://fleet-default:services-shared-cloudprovider
cluster:
  annotations: {}
  labels:
    environment: services
    cluster_name: shared
    location: deathstar
  name: services-shared
kubernetesVersion: v1.24.7+rke2r1
monitoring:
  enabled: false
registries:
  configs:
    rgcrprod.azurecr.us:
      authConfigSecretName: carbide-registry
      caBundle: ''
      insecureSkipVerify: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: false
  displayName: control-plane-nodes
  name: control-plane-svc-pool
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/services
  networkType: dhcp
  imageName: default/ubuntu-rke2-airgap-harvester
  vmNamespace: default
  sshUser: ubuntu
  userData: ""
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-nodes
  name: worker-svc-pool
  labels: {}
  taints: {}
  quantity: 3
  paused: false
  diskSize: 40
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/services
  networkType: dhcp
  imageName: default/ubuntu-rke2-airgap-harvester
  vmNamespace: default
  sshUser: ubuntu
  userData: ""