cloudprovider: harvester
cloudCredentialSecretName: cattle-global-data:cc-rvdh4
cluster:
  annotations: {}
  labels:
    environment: services
    cluster_name: shared
    location: deathstar
  name: services-shared
kubernetesVersion: v1.24.7+rke2r1
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: false
  displayName: control-plane-nodes
  name: control-plane-svc-pool
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/services
  networkType: dhcp
  imageName: default/ubuntu-2004
  vmNamespace: default
  sshUser: ubuntu
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-nodes
  name: worker-svc-pool
  labels: {}
  taints: {}
  quantity: 3
  paused: false
  diskSize: 250
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/services
  networkType: dhcp
  imageName: default/ubuntu-2004
  vmNamespace: default
  sshUser: ubuntu
