cloudprovider: harvester
cloudCredentialSecretName: cattle-global-data:cc-k7j9v
cluster:
  annotations: {}
  labels:
    environment: dev
    cluster_name: fluffymunchkin
    location: deathstar
  name: dev-fluffymunchkin
kubernetesVersion: v1.24.7+rke2r1
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: true
  displayName: control-plane-nodes
  name: control-plane-dev-pool
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/dev
  networkType: dhcp
  imageName: default/ubuntu-2004
  vmNamespace: default
  sshUser: ubuntu
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-nodes
  name: worker-dev-pool
  labels: {}
  taints: {}
  quantity: 2
  paused: false
  diskSize: 100
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/dev
  networkType: dhcp
  imageName: default/ubuntu-2004
  vmNamespace: default
  sshUser: ubuntu
