kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: essentials
  namespace: fleet-default
spec:
  repo: https://github.com/bcdurden/deathstar_builder.git
  branch: main

  targets:
  - clusterSelector:
      matchLabels:
        location: el8000

  paths:
  - "./gitops/apps/essentials"